# Generated by Django 6.0.2 on 2026-02-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ویدیو')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('video_url', models.URLField(verbose_name='لینک ویدیو (یوتیوب)')),
                ('is_english', models.BooleanField(default=False, verbose_name='انگلیسی هست؟')),
                ('subtitle_url', models.URLField(blank=True, verbose_name='لینک زیرنویس فارسی')),
                ('dubbed_url', models.URLField(blank=True, verbose_name='لینک دوبله فارسی')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
