# Generated by Django 6.0.2 on 2026-02-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_educationalvideo_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='فایل ویدیو mp4'),
        ),
        migrations.AlterField(
            model_name='educationalvideo',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='لینک ویدیو (یوتیوب)'),
        ),
    ]
