# Generated by Django 6.0.2 on 2026-02-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_educationalvideo_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalvideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='educationalvideo',
            name='direct_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک مستقیم mp4 (برای پخش داخل سایت)'),
        ),
        migrations.AddField(
            model_name='educationalvideo',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک یوتیوب (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='educationalvideo',
            name='dubbed_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک دوبله فارسی'),
        ),
        migrations.AlterField(
            model_name='educationalvideo',
            name='subtitle_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک زیرنویس فارسی'),
        ),
        migrations.AlterField(
            model_name='educationalvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='فایل ویدیو mp4 (اختیاری)'),
        ),
    ]
