# Generated by Django 6.0.2 on 2026-02-27 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_educationalvideo_video_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalvideo',
            name='min_watch_seconds',
            field=models.PositiveIntegerField(default=30, verbose_name='حداقل زمان برای جایزه (ثانیه)'),
        ),
        migrations.AddField(
            model_name='educationalvideo',
            name='xp_reward',
            field=models.PositiveIntegerField(default=20, verbose_name='جایزه XP'),
        ),
        migrations.CreateModel(
            name='WatchedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_videos', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_records', to='videos.educationalvideo')),
            ],
            options={
                'verbose_name': 'ویدیوی دیده\u200cشده',
                'verbose_name_plural': 'ویدیوهای دیده\u200cشده',
                'unique_together': {('user', 'video')},
            },
        ),
    ]
