# Generated by Django 6.0.2 on 2026-02-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام بازی')),
                ('description', models.TextField(verbose_name='توضیح کوتاه')),
                ('xp_reward', models.PositiveIntegerField(default=50, verbose_name='امتیاز جایزه')),
            ],
        ),
    ]
