# Generated by Django 6.0.2 on 2026-02-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_completedgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamechallenge',
            name='code_template',
            field=models.TextField(blank=True, verbose_name='قالب کد اولیه'),
        ),
        migrations.AddField(
            model_name='gamechallenge',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='درجه سختی'),
        ),
        migrations.AddField(
            model_name='gamechallenge',
            name='expected_output',
            field=models.TextField(blank=True, verbose_name='خروجی مورد انتظار'),
        ),
        migrations.AddField(
            model_name='gamechallenge',
            name='hints',
            field=models.TextField(blank=True, verbose_name='راهنمایی\u200cها (اختیاری)'),
        ),
        migrations.AddField(
            model_name='gamechallenge',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='راهنما/قوانین بازی'),
        ),
        migrations.AddField(
            model_name='gamechallenge',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
